version: "3"
services:
  database:
    image: mysql
    container_name: test-filter-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: elijah
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: database
    ports:
     - "33062:3306"

  app:
    build: docker
    container_name: test-filter-app
    working_dir: /app
    volumes:
        - .:/app
